# Generated by Django 2.2.3 on 2019-08-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20190805_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencepagecomment',
            name='comment',
            field=models.TextField(blank=True, max_length=1250),
        ),
    ]
