# Generated by Django 2.2.3 on 2019-08-09 11:01
# Based on learning from https://stackoverflow.com/questions/55941737/how-to-migrate-richtextfield-to-streamfield

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import json
from wagtail.core.rich_text import RichText


def convert_data(apps, schema_editor):
    for name in ['intro', 'thank_you_text']:
        FormPage = apps.get_model('teratree', 'FormPage')
        for form in FormPage.objects.all():
            print('\n', form.title)
            # edit the live form page
            if getattr(form, name).raw_text and not getattr(form, name):
                setattr(form, name, [('paragraph', RichText(getattr(form, name).raw_text))])
                print('Updated ' + form.title)
                form.save()

            # # edit drafts associated with post
            # if form.has_unpublished_changes:
            print(form.title + ' has revisions...')
            for rev in form.revisions.all():
                data = json.loads(rev.content_json)
                value = data[name]
                print(value)

                print('This is current JSON:', data, '\n')
                data[name] = json.dumps([{
                    "type": "paragraph",
                    "value": value
                }])
                rev.content_json = json.dumps(data)
                print('This is updated JSON:', rev.content_json, '\n')

                rev.save()

            print('Completed ' + form.title + '.' + '\n')


class Migration(migrations.Migration):

    dependencies = [
        ('teratree', '0002_formfield_formpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='outro',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='intro',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.RunPython(convert_data),
    ]
