# Generated by Django 2.2.1 on 2019-05-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190512_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(default='Intro', max_length=250),
            preserve_default=False,
        ),
    ]
