# Generated by Django 2.2.1 on 2019-05-14 06:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190513_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.DateField(verbose_name='Post date')),
                ('author', models.CharField(blank=True, max_length=250)),
                ('comment', models.CharField(blank=True, max_length=1250)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.BlogPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
