# Generated by Django 2.2.1 on 2019-05-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpagecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='time',
            field=models.TimeField(default='12:00', verbose_name='Post time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpagecomment',
            name='date',
            field=models.DateTimeField(verbose_name='Post date'),
        ),
    ]
