# Generated by Django 2.2.3 on 2019-08-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20190518_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagecomment',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='blogpagecomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_page_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
