# Generated by Django 2.2.3 on 2019-08-02 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190802_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpagecomment',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='blogpagecomment',
            name='date',
        ),
        migrations.AddField(
            model_name='blogpagecomment',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
