# Generated by Django 2.2.3 on 2019-08-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190802_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagecomment',
            name='comment',
            field=models.TextField(blank=True, max_length=1250),
        ),
    ]
