# Generated by Django 2.2.3 on 2019-07-23 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiment', '0002_delete_results00001data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions00001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, default='', help_text='Where did they answer?', max_length=254)),
                ('question1', models.TextField(blank=True, default='', help_text='When did you last plant a tree?')),
                ('question2', models.TextField(blank=True, default='', help_text='If I gave you a tree tomorrow what would you do with it?')),
                ('question3', models.TextField(blank=True, default='', help_text='How would you get a tree?')),
                ('cczero', models.BooleanField(default=False, help_text='Can we put your name and answers online under a cczero license so others can use them?')),
                ('respondant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response_to_000001', to='experiment.Person')),
            ],
        ),
    ]
