# Generated by Django 2.2.3 on 2019-07-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions00001',
            options={'verbose_name_plural': 'questions00001'},
        ),
    ]
