# Generated by Django 2.2.3 on 2019-08-02 15:46

from django.db import migrations, models

def nothing(apps, schema_editor):
    pass

def copy_person(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model('experiment', 'Person')
    Questions00001 = apps.get_model('data', 'Questions00001')
    for survey in Questions00001.objects.all():
        survey.first_name = survey.respondant.first_name
        survey.last_name = survey.respondant.last_name
        survey.email = survey.respondant.email
        survey.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190724_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions00001',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='questions00001',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='questions00001',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.RunPython(copy_person, nothing),
        migrations.RemoveField(
            model_name='questions00001',
            name='respondant',
        ),
    ]
